# Generated by Django 3.2 on 2023-11-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesuration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=50)),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ModelsTenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=50)),
                ('temps_execution', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tailleur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idUser', models.CharField(max_length=255)),
                ('nomAtelier', models.CharField(max_length=255)),
                ('Adresse', models.CharField(max_length=255)),
                ('competance', models.CharField(max_length=255)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('catalogueModel', models.ManyToManyField(to='api.ModelsTenue')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_voted', models.BooleanField()),
                ('nbr_etoile', models.IntegerField()),
                ('tailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tailleur')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('recetteMontant', models.CharField(max_length=255)),
                ('recetteDate', models.DateField()),
                ('idTailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tailleur')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_annee', models.DateField()),
                ('tenues_confectionnees', models.PositiveIntegerField()),
                ('argent_genere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clients_rentables', models.ManyToManyField(to='api.Client')),
                ('models_vogues', models.ManyToManyField(to='api.ModelsTenue')),
                ('tailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tailleur')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('depenseMontant', models.CharField(max_length=255)),
                ('depenseDate', models.DateField()),
                ('idTailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tailleur')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phoneNumber', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('birthday', models.DateField()),
                ('address', models.JSONField()),
                ('gender', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('idRoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=255)),
                ('dateCommande', models.DateField()),
                ('dateLivraison', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titre', models.CharField(max_length=255)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to='api.customuser')),
                ('idModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelstenue')),
                ('idTailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tailleur')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
        ),
        migrations.AddField(
            model_name='client',
            name='modelfavoris',
            field=models.ManyToManyField(to='api.ModelsTenue'),
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('idImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('tailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tailleur')),
            ],
        ),
    ]
