# Generated by Django 3.2 on 2023-11-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='lastname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modelstenue',
            old_name='lastname',
            new_name='name',
        ),
    ]
