# Generated by Django 3.2 on 2023-11-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='lastname',
            new_name='name',
        ),
    ]
